
export const isLogged = state =>
  state.loginReducer.loggedIn

export const getToken = state => 
  state.loginReducer.token 

export const getUser = state => 
  state.loginReducer.user 

  // ({accessToken:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3NWVlYWY2Ni1mY2E0LTRiNDktOGY0MC0zZGFlNDFjNzlhNTEiLCJmdWxsTmFtZSI6IktodWUgUGhhbSIsImZpcnN0TmFtZSI6IktodWUiLCJsYXN0TmFtZSI6IlBoYW0iLCJlbWFpbCI6W10sImF2YXRhciI6Imh0dHBzOi8vZ3JhcGguZmFjZWJvb2suY29tLzY4NjEwNjU0MTU0Mjg2Ni9waWN0dXJlP3R5cGU9bGFyZ2UiLCJwcm92aWRlciI6W3sicElkIjoiNjg2MTA2NTQxNTQyODY2IiwidHlwZSI6ImZhY2Vib29rIiwiYWNjZXNzVG9rZW4iOiJFQUFaQXhlc3oxOWlVQkFJbERKVWtaQkhjOXFZdnRvd3c3RDZCSEdOWVpBSEd4RlpDNUt3cXJtWU9KUDZpeGpOQzN1MWZQdktoRFFSeVFpaGVaQ1h2cXZWMEo0UGx6dlNHQ3VITUNBVzBkZE0zVlkzNjhnMU1NMHZ3WkFDeEZhWUpsdUgwSm1EZ3RLQUpMYnZBTFZZWkNGcHcwcEpwZGRBdGtvWkQifV0sImlhdCI6MTQ3ODQwNzUxMiwiZXhwIjoxNDc5MDEyMzEyfQ.AbShQCsE43uBIKe3FMTill3ulrNs_A57LNNfv79m6hk'})